Adding convenience method for NNS
Spiess/cottontaildb-python-client pull request #18
Opened 2023-03-27 19:11 UTC by silvanheller

Inspired by #17, this PR adds a convenience method to the client for NNS search akin to what the SimpleClient has. It also adds a test for this function

2023-03-27 19:24 UTC, Spiess commented on cottontaildb_client/cottontaildb_client.py
> +        fn = FunctionName(name='euclidean')
Is it possible the caller provided distance function is never used?
I can't find any reference to it and `euclidean` appears hard-coded.

2023-03-27 19:51 UTC, silvanheller commented
Updated & fixed copy-paste errors

2023-03-28 07:09 UTC, Spiess requested changes
Thanks for the fix and the work it looks great!
I overlooked some minor PEP violations in my first review, after those are fixed we can merge.

2023-03-28 07:09 UTC, Spiess commented on tests/test_cottontaildb_client.py
> +
PEP 8: E303 too many blank lines

2023-03-28 07:09 UTC, Spiess commented on tests/test_cottontaildb_client.py
> +    Order
Please remove unused imports

2023-03-28 07:09 UTC, Spiess commented on cottontaildb_client/cottontaildb_client.py
> +        projection = Projection(op=Projection.ProjectionOperation.SELECT, elements=[projection_element, Projection.ProjectionElement(expression=idExpression)])
PEP 8 E501: line too long
Please autoformat to wrap this line

2023-03-28 07:09 UTC, Spiess commented on cottontaildb_client/cottontaildb_client.py
> +        idExpression = Expression(column=ColumnName(name=id_col))
Please refactor variable names to snake_case. While not as important as `idExpression`, I would prefer to also split names like `distancecol` to `distance_col`.

2023-03-28 09:11 UTC, Spiess approved these changes

2023-03-28 09:11 UTC, merged